#!/bin/bash

action=$1
shift

function usage(){
  echo "  Navigate to URI:"
  echo "    uri ITEM#"
  echo "      Searches for a URI in the todo line and launches it"
  echo ""
  exit
}

[ "$action" = "usage" ] && usage

if ! [[ "$1" =~ ^[0-9]+$ ]]; then
    echo "Error! Usage:"
    usage
fi

URI=$(sed "$1!d" "$TODO_FILE"|grep -E -o "\"[A-Z]:[/\|\\].*\"")


if [ "$URI" = "" ]; then    
	LINE=$(sed "$1!d" "$TODO_FILE")	
    if [ "$LINE" = "" ]; then
        echo "Error, no item #$1 found!"
    else
        echo "Error, no URL seen in item #$1!"
        echo "$LINE"
    fi
    exit 1
fi

cygstart "explorer" "$URI"
